# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 3178be9bf9392b26911742a448480bb10bbbafa51d3e44caea8177242dd990d72ce4bb1551d01a468de624b944de04a39a611b0a4c2f0c5d30014d2609135d52

test:
  secret_key_base: a60d771770ff6d04d57e13e93cdc869927019790ecf28739ee55b1bcbf7d2bdd561b2e0038fb9de18b46b9f7f50beeca7f45760bd111d769176e651e81fe07f8

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
